### ISSUE TITLE
这个项目在STM32F103上能运行不？

### ISSUE THREAD

**Issue by e0r** [yitiandelan/ZLCR#2]
按官方手册的数据1.25 DMIPS/MHz，F103默频都有90DMIPS了。能移植的话成本能降很多，，

**Comment by yitiandelan** [comment]
没有fpu，不能



发送自Windows 10 版邮件应用


-------- 原始信息 --------
发件人： e0r <notifications@github.com>
日期: 2018/11/25 20:32 (GMT+08:00)
收件人： yitiandelan/ZLCR <ZLCR@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [yitiandelan/ZLCR] 这个项目在STM32F103上能运行不？ (#2)


按官方手册的数据1.25 DMIPS/MHz，F103默频都有90DMIPS了。能移植的话成本能降很多，，

―

**Comment by e0r** [comment]
MK66FX1M0VLQ18
这个呢？NXP的K66系列，虽然也是冷门芯片，不过NXP对样片友好，STM根本不可能有样片的。
集成双16位ADC 双12位dac，还有一款芯片带四个PGA，不过没样片而且买都买不到。
