### ISSUE TITLE
100k ZLCR.rev.c.pdf这个文件失效了能补一下吗

### ISSUE THREAD

**Issue by ningmen7294** [yitiandelan/ZLCR#3]
100k ZLCR.rev.c.pdf这个文件失效了能补一下吗

**Comment by yitiandelan** [comment]
在提交历史或release中可以找到，如果有下个版本主控会选fpga


发送自Windows 10 版邮件应用


-------- 原始信息 --------
发件人： alan <notifications@github.com>
日期: 2019/3/29 21:27 (GMT+08:00)
收件人： yitiandelan/ZLCR <ZLCR@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [yitiandelan/ZLCR] 100k ZLCR.rev.c.pdf这个文件失效了能补一下吗 (#3)


100k ZLCR.rev.c.pdf这个文件失效了能补一下吗

―
