### ISSUE TITLE
照着做了一版，数据是乱的，请问哪里大概哪里不对

### ISSUE THREAD

**Issue by yaojinghui** [yitiandelan/ZLCR#6]
{"FREQ":1.000000e+03,"a":-6.912640e-01,"b":-8.410071e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-1.393929e-01,"b":-3.278058e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":6.741095e-01,"b":1.503216e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":7.097892e-01,"b":2.585490e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-1.231647e-01,"b":1.138702e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":3.095914e-01,"b":-1.331556e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":9.843286e-01,"b":-5.385807e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-1.039570e+00,"b":-9.697864e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-4.384388e+00,"b":-1.000553e+01,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-4.910255e+00,"b":-4.974035e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-2.387659e+00,"b":1.167496e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-7.310057e-01,"b":4.182962e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-2.229830e+00,"b":3.920526e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-4.582276e+00,"b":1.929598e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-4.444520e+00,"b":-2.528647e-01,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-1.740824e+00,"b":-9.620521e-01,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-1.221070e-02,"b":-1.707922e-01,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-4.054714e-01,"b":2.911497e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-3.676636e+00,"b":4.279772e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-6.603706e+00,"b":3.044393e+00,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-8.903024e+00,"b":-7.105184e-01,"c":-1.054918e-35,"d":1.055024e-35}
{"FREQ":1.000000e+03,"a":-1.030009e+01,"b":-3.080566e+00,"c":-1.054918e-35,"d":1.055024e-35}

**Comment by yitiandelan** [comment]
无法复现你的问题，但至少串口，滤波器和 RTOS 是正常工作，请检查你的电路板，简单的方法是示波器观察激励 1 kHz 信号，如果不是，检查 I2S 和 I2C 信号是否正常
