### ISSUE TITLE
文件上传不完整，打不开？

### ISSUE THREAD

**Issue by terenceyhj** [yitiandelan/ZLCR#7]
文件上传不完整，打不开？

**Comment by yitiandelan** [comment]
如果是 git clone 报错，安装：git-lfs


-------- 原始信息 --------
发件人： terenceyhj <notifications@github.com>
日期: 2020/8/6 04:28 (GMT+08:00)
收件人： yitiandelan/ZLCR <ZLCR@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [yitiandelan/ZLCR] 文件上传不完整，打不开？ (#7)


文件上传不完整，打不开？

―

**Comment by terenceyhj** [comment]
..\ZLCR\doc\res下的图片大小只有1k.是否是未传完整！

**Comment by terenceyhj** [comment]
谢谢！！！是 git pull后不完整，重新git clone就好了！！！
