### ISSUE TITLE
这个单片机程序怎么编译啊

### ISSUE THREAD

**Issue by e0r** [yitiandelan/ZLCR#9]

**Comment by yitiandelan** [comment]
gn build && ninja -C build

ref:
* .vscode/tasks.json
* .devcontainer/Dockerfile

**Comment by e0r** [comment]
> gn build && ninja -C build ref: * .vscode/tasks.json * .devcontainer/Dockerfile

为啥我编译出来的程序没反应啊，发送zlcr -raw -f 1000啥都没出来，烧你那个hex就能用

**Comment by e0r** [comment]
而且两个夹子接一起RS都是几欧

**Comment by yitiandelan** [comment]
![Screenshot_20210826_183408](https://user-images.githubusercontent.com/9023266/130948050-820e3721-d330-469b-88b6-093c48e2e8a8.png)

**Comment by e0r** [comment]
刚又编译了一下，在命令行下能用，不过和C#程序不兼容，程序没反应
